### ISSUE TITLE
Bypass limitation

### ISSUE THREAD

**Issue by Sallie-May** [Zapak69/bat-encrypt#1]
Just go into your registry key
HKCU\Software\Bat-Encrypt
and change free use to 0

or use this CMD command
```reg  add "HKCU\Software\Bat-Encrypt" /v FreeUses /t REG_SZ /d "0" /f```

**Comment by Zapak69** [comment]
It should be fixed

**Comment by Sallie-May** [comment]
C:\Windows\system32\cmd.exe /c reg query "HKCU\Software\Bat-Encrypt" /v ActivateDate
PID:1224
C:\Windows\system32\reg.exe
reg  query "HKCU\Software\Bat-Encrypt" /v ActivateDate

just delete the query on this path and ur good

**Comment by Zapak69** [comment]
nope, activate date is something other just try and you will see
